name: Build and push images
on:
  push:
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract versions of vscode & tofu
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          VSCODE_VERSION=$(echo "$BRANCH_NAME" | sed -n 's/.*vscode-\([0-9.]*\).*/\1/p')
          TOFU_VERSION=$(echo "$BRANCH_NAME" | sed -n 's/.*tofu-\([0-9.]*\).*/\1/p')
          echo "VSCODE_VERSION=$VSCODE_VERSION" >> $GITHUB_ENV
          echo "TOFU_VERSION=$TOFU_VERSION" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64,linux/amd64
          context: .
          file: Dockerfile
          push: true
          tags: "ghcr.io/${{ github.actor }}/vscode:${{ env.VSCODE_VERSION }}-${{ env.TOFU_VERSION }}"
          build-args: |
            VSCODE_VERSION=${{ env.VSCODE_VERSION }}
            TOFU_VERSION=${{ env.TOFU_VERSION }}
